services:
  blog-server:
    build: .
    container_name: blog-server
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=blog
      - REDIS_ADDR=redis:6379
    networks:
      - app-network

  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog
    ports:
      - "3307:3306"   # 宿主机访问端口改为 3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  redis:
    image: redis:8.2.1
    container_name: redis
    restart: always
    ports:
      - "6380:6379"   # 宿主机访问端口改为 6380
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge


