services:
  frontend:
    build: ./frontend
    container_name: blog_frontend
    restart: always
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=production
    depends_on:
     - backend

  backend:
    build: ./backend
    container_name: blog_backend
    restart: always
    ports:
     - "8000:8000"
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - POSTGRES_HOST=postgres
     - POSTGRES_PORT=5432
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=mydb
    volumes:
     - /etc/blog/backend/config.yml:/etc/backend/config.yaml:ro
    depends_on:
     - redis
     - postgres

  redis:
    image: docker.io/redis:8-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: docker.io/postgres:18-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: docker.io/nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/blog/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
