# 构建阶段
FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./cmd/

# 运行阶段
FROM debian:bookworm-slim
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8000
CMD ["./main"]

