// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCategoryCreate is the builder for creating a LinkCategory entity.
type LinkCategoryCreate struct {
	config
	mutation *LinkCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCategoryCreate) SetCreatedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableCreatedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkCategoryCreate) SetUpdatedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableUpdatedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *LinkCategoryCreate) SetDeletedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableDeletedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LinkCategoryCreate) SetName(v string) *LinkCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LinkCategoryCreate) SetSortOrder(v int) *LinkCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableSortOrder(v *int) *LinkCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCategoryCreate) SetID(v uint) *LinkCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddLinkIDs adds the "links" edge to the Link entity by IDs.
func (_c *LinkCategoryCreate) AddLinkIDs(ids ...uint) *LinkCategoryCreate {
	_c.mutation.AddLinkIDs(ids...)
	return _c
}

// AddLinks adds the "links" edges to the Link entity.
func (_c *LinkCategoryCreate) AddLinks(v ...*Link) *LinkCategoryCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLinkIDs(ids...)
}

// Mutation returns the LinkCategoryMutation object of the builder.
func (_c *LinkCategoryCreate) Mutation() *LinkCategoryMutation {
	return _c.mutation
}

// Save creates the LinkCategory in the database.
func (_c *LinkCategoryCreate) Save(ctx context.Context) (*LinkCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCategoryCreate) SaveX(ctx context.Context) *LinkCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCategoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := linkcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := linkcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := linkcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCategoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LinkCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LinkCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := linkcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LinkCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "LinkCategory.sort_order"`)}
	}
	return nil
}

func (_c *LinkCategoryCreate) sqlSave(ctx context.Context) (*LinkCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCategoryCreate) createSpec() (*LinkCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkcategory.Table, sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(linkcategory.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(linkcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(linkcategory.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCategory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCategoryCreate) OnConflict(opts ...sql.ConflictOption) *LinkCategoryUpsertOne {
	_c.conflict = opts
	return &LinkCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCategoryCreate) OnConflictColumns(columns ...string) *LinkCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCategoryUpsertOne{
		create: _c,
	}
}

type (
	// LinkCategoryUpsertOne is the builder for "upsert"-ing
	//  one LinkCategory node.
	LinkCategoryUpsertOne struct {
		create *LinkCategoryCreate
	}

	// LinkCategoryUpsert is the "OnConflict" setter.
	LinkCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *LinkCategoryUpsert) SetCreatedAt(v time.Time) *LinkCategoryUpsert {
	u.Set(linkcategory.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkCategoryUpsert) UpdateCreatedAt() *LinkCategoryUpsert {
	u.SetExcluded(linkcategory.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCategoryUpsert) SetUpdatedAt(v time.Time) *LinkCategoryUpsert {
	u.Set(linkcategory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCategoryUpsert) UpdateUpdatedAt() *LinkCategoryUpsert {
	u.SetExcluded(linkcategory.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkCategoryUpsert) SetDeletedAt(v time.Time) *LinkCategoryUpsert {
	u.Set(linkcategory.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkCategoryUpsert) UpdateDeletedAt() *LinkCategoryUpsert {
	u.SetExcluded(linkcategory.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkCategoryUpsert) ClearDeletedAt() *LinkCategoryUpsert {
	u.SetNull(linkcategory.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *LinkCategoryUpsert) SetName(v string) *LinkCategoryUpsert {
	u.Set(linkcategory.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkCategoryUpsert) UpdateName() *LinkCategoryUpsert {
	u.SetExcluded(linkcategory.FieldName)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCategoryUpsert) SetSortOrder(v int) *LinkCategoryUpsert {
	u.Set(linkcategory.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCategoryUpsert) UpdateSortOrder() *LinkCategoryUpsert {
	u.SetExcluded(linkcategory.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCategoryUpsert) AddSortOrder(v int) *LinkCategoryUpsert {
	u.Add(linkcategory.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(linkcategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkCategoryUpsertOne) UpdateNewValues() *LinkCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(linkcategory.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkCategoryUpsertOne) Ignore() *LinkCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCategoryUpsertOne) DoNothing() *LinkCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCategoryCreate.OnConflict
// documentation for more info.
func (u *LinkCategoryUpsertOne) Update(set func(*LinkCategoryUpsert)) *LinkCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LinkCategoryUpsertOne) SetCreatedAt(v time.Time) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertOne) UpdateCreatedAt() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCategoryUpsertOne) SetUpdatedAt(v time.Time) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertOne) UpdateUpdatedAt() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkCategoryUpsertOne) SetDeletedAt(v time.Time) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertOne) UpdateDeletedAt() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkCategoryUpsertOne) ClearDeletedAt() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *LinkCategoryUpsertOne) SetName(v string) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkCategoryUpsertOne) UpdateName() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCategoryUpsertOne) SetSortOrder(v int) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCategoryUpsertOne) AddSortOrder(v int) *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCategoryUpsertOne) UpdateSortOrder() *LinkCategoryUpsertOne {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *LinkCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkCategoryUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkCategoryUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCategoryCreateBulk is the builder for creating many LinkCategory entities in bulk.
type LinkCategoryCreateBulk struct {
	config
	err      error
	builders []*LinkCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the LinkCategory entities in the database.
func (_c *LinkCategoryCreateBulk) Save(ctx context.Context) ([]*LinkCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCategoryCreateBulk) SaveX(ctx context.Context) []*LinkCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkCategoryUpsertBulk {
	_c.conflict = opts
	return &LinkCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCategoryCreateBulk) OnConflictColumns(columns ...string) *LinkCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCategoryUpsertBulk{
		create: _c,
	}
}

// LinkCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of LinkCategory nodes.
type LinkCategoryUpsertBulk struct {
	create *LinkCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(linkcategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkCategoryUpsertBulk) UpdateNewValues() *LinkCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(linkcategory.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkCategoryUpsertBulk) Ignore() *LinkCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCategoryUpsertBulk) DoNothing() *LinkCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *LinkCategoryUpsertBulk) Update(set func(*LinkCategoryUpsert)) *LinkCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LinkCategoryUpsertBulk) SetCreatedAt(v time.Time) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertBulk) UpdateCreatedAt() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCategoryUpsertBulk) SetUpdatedAt(v time.Time) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertBulk) UpdateUpdatedAt() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkCategoryUpsertBulk) SetDeletedAt(v time.Time) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkCategoryUpsertBulk) UpdateDeletedAt() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkCategoryUpsertBulk) ClearDeletedAt() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *LinkCategoryUpsertBulk) SetName(v string) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkCategoryUpsertBulk) UpdateName() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCategoryUpsertBulk) SetSortOrder(v int) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCategoryUpsertBulk) AddSortOrder(v int) *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCategoryUpsertBulk) UpdateSortOrder() *LinkCategoryUpsertBulk {
	return u.Update(func(s *LinkCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *LinkCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
