// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"blog-server/entity"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCreate) SetCreatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCreatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkCreate) SetUpdatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableUpdatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *LinkCreate) SetDeletedAt(v time.Time) *LinkCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDeletedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LinkCreate) SetDescription(v string) *LinkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDescription(v *string) *LinkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LinkCreate) SetEnabled(v bool) *LinkCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LinkCreate) SetNillableEnabled(v *bool) *LinkCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LinkCreate) SetName(v string) *LinkCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LinkCreate) SetSortOrder(v int) *LinkCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LinkCreate) SetNillableSortOrder(v *int) *LinkCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *LinkCreate) SetURL(v string) *LinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetAvatar sets the "avatar" field.
func (_c *LinkCreate) SetAvatar(v string) *LinkCreate {
	_c.mutation.SetAvatar(v)
	return _c
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_c *LinkCreate) SetNillableAvatar(v *string) *LinkCreate {
	if v != nil {
		_c.SetAvatar(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LinkCreate) SetStatus(v entity.LinkStatus) *LinkCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LinkCreate) SetNillableStatus(v *entity.LinkStatus) *LinkCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *LinkCreate) SetCategoryID(v uint) *LinkCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCategoryID(v *uint) *LinkCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCreate) SetID(v uint) *LinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (_c *LinkCreate) SetCategory(v *LinkCategory) *LinkCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (_c *LinkCreate) Mutation() *LinkMutation {
	return _c.mutation
}

// Save creates the Link in the database.
func (_c *LinkCreate) Save(ctx context.Context) (*Link, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := link.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := link.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := link.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := link.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := link.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Link.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Link.updated_at"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := link.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Link.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Link.enabled"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Link.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Link.sort_order"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Link.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Avatar(); ok {
		if err := link.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Link.avatar": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Link.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(link.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(link.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(link.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(link.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Avatar(); ok {
		_spec.SetField(link.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Link.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCreate) OnConflict(opts ...sql.ConflictOption) *LinkUpsertOne {
	_c.conflict = opts
	return &LinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCreate) OnConflictColumns(columns ...string) *LinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkUpsertOne{
		create: _c,
	}
}

type (
	// LinkUpsertOne is the builder for "upsert"-ing
	//  one Link node.
	LinkUpsertOne struct {
		create *LinkCreate
	}

	// LinkUpsert is the "OnConflict" setter.
	LinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *LinkUpsert) SetCreatedAt(v time.Time) *LinkUpsert {
	u.Set(link.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkUpsert) UpdateCreatedAt() *LinkUpsert {
	u.SetExcluded(link.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkUpsert) SetUpdatedAt(v time.Time) *LinkUpsert {
	u.Set(link.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkUpsert) UpdateUpdatedAt() *LinkUpsert {
	u.SetExcluded(link.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkUpsert) SetDeletedAt(v time.Time) *LinkUpsert {
	u.Set(link.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkUpsert) UpdateDeletedAt() *LinkUpsert {
	u.SetExcluded(link.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkUpsert) ClearDeletedAt() *LinkUpsert {
	u.SetNull(link.FieldDeletedAt)
	return u
}

// SetDescription sets the "description" field.
func (u *LinkUpsert) SetDescription(v string) *LinkUpsert {
	u.Set(link.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LinkUpsert) UpdateDescription() *LinkUpsert {
	u.SetExcluded(link.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *LinkUpsert) ClearDescription() *LinkUpsert {
	u.SetNull(link.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *LinkUpsert) SetEnabled(v bool) *LinkUpsert {
	u.Set(link.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkUpsert) UpdateEnabled() *LinkUpsert {
	u.SetExcluded(link.FieldEnabled)
	return u
}

// SetName sets the "name" field.
func (u *LinkUpsert) SetName(v string) *LinkUpsert {
	u.Set(link.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkUpsert) UpdateName() *LinkUpsert {
	u.SetExcluded(link.FieldName)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkUpsert) SetSortOrder(v int) *LinkUpsert {
	u.Set(link.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkUpsert) UpdateSortOrder() *LinkUpsert {
	u.SetExcluded(link.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkUpsert) AddSortOrder(v int) *LinkUpsert {
	u.Add(link.FieldSortOrder, v)
	return u
}

// SetURL sets the "url" field.
func (u *LinkUpsert) SetURL(v string) *LinkUpsert {
	u.Set(link.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsert) UpdateURL() *LinkUpsert {
	u.SetExcluded(link.FieldURL)
	return u
}

// SetAvatar sets the "avatar" field.
func (u *LinkUpsert) SetAvatar(v string) *LinkUpsert {
	u.Set(link.FieldAvatar, v)
	return u
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *LinkUpsert) UpdateAvatar() *LinkUpsert {
	u.SetExcluded(link.FieldAvatar)
	return u
}

// ClearAvatar clears the value of the "avatar" field.
func (u *LinkUpsert) ClearAvatar() *LinkUpsert {
	u.SetNull(link.FieldAvatar)
	return u
}

// SetStatus sets the "status" field.
func (u *LinkUpsert) SetStatus(v entity.LinkStatus) *LinkUpsert {
	u.Set(link.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LinkUpsert) UpdateStatus() *LinkUpsert {
	u.SetExcluded(link.FieldStatus)
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *LinkUpsert) SetCategoryID(v uint) *LinkUpsert {
	u.Set(link.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *LinkUpsert) UpdateCategoryID() *LinkUpsert {
	u.SetExcluded(link.FieldCategoryID)
	return u
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *LinkUpsert) ClearCategoryID() *LinkUpsert {
	u.SetNull(link.FieldCategoryID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(link.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkUpsertOne) UpdateNewValues() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(link.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkUpsertOne) Ignore() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkUpsertOne) DoNothing() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCreate.OnConflict
// documentation for more info.
func (u *LinkUpsertOne) Update(set func(*LinkUpsert)) *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LinkUpsertOne) SetCreatedAt(v time.Time) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateCreatedAt() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkUpsertOne) SetUpdatedAt(v time.Time) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateUpdatedAt() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkUpsertOne) SetDeletedAt(v time.Time) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateDeletedAt() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkUpsertOne) ClearDeletedAt() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDescription sets the "description" field.
func (u *LinkUpsertOne) SetDescription(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateDescription() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LinkUpsertOne) ClearDescription() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LinkUpsertOne) SetEnabled(v bool) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateEnabled() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateEnabled()
	})
}

// SetName sets the "name" field.
func (u *LinkUpsertOne) SetName(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateName() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkUpsertOne) SetSortOrder(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkUpsertOne) AddSortOrder(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateSortOrder() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateSortOrder()
	})
}

// SetURL sets the "url" field.
func (u *LinkUpsertOne) SetURL(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateURL() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateURL()
	})
}

// SetAvatar sets the "avatar" field.
func (u *LinkUpsertOne) SetAvatar(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateAvatar() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *LinkUpsertOne) ClearAvatar() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.ClearAvatar()
	})
}

// SetStatus sets the "status" field.
func (u *LinkUpsertOne) SetStatus(v entity.LinkStatus) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateStatus() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateStatus()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *LinkUpsertOne) SetCategoryID(v uint) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateCategoryID() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *LinkUpsertOne) ClearCategoryID() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.ClearCategoryID()
	})
}

// Exec executes the query.
func (u *LinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkUpsertOne) ID(ctx context.Context) (id uint, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkUpsertOne) IDX(ctx context.Context) uint {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
	conflict []sql.ConflictOption
}

// Save creates the Link entities in the database.
func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Link, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Link.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkUpsertBulk {
	_c.conflict = opts
	return &LinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCreateBulk) OnConflictColumns(columns ...string) *LinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkUpsertBulk{
		create: _c,
	}
}

// LinkUpsertBulk is the builder for "upsert"-ing
// a bulk of Link nodes.
type LinkUpsertBulk struct {
	create *LinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(link.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkUpsertBulk) UpdateNewValues() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(link.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkUpsertBulk) Ignore() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkUpsertBulk) DoNothing() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCreateBulk.OnConflict
// documentation for more info.
func (u *LinkUpsertBulk) Update(set func(*LinkUpsert)) *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *LinkUpsertBulk) SetCreatedAt(v time.Time) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateCreatedAt() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkUpsertBulk) SetUpdatedAt(v time.Time) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateUpdatedAt() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *LinkUpsertBulk) SetDeletedAt(v time.Time) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateDeletedAt() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *LinkUpsertBulk) ClearDeletedAt() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDescription sets the "description" field.
func (u *LinkUpsertBulk) SetDescription(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateDescription() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LinkUpsertBulk) ClearDescription() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LinkUpsertBulk) SetEnabled(v bool) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateEnabled() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateEnabled()
	})
}

// SetName sets the "name" field.
func (u *LinkUpsertBulk) SetName(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateName() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateName()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkUpsertBulk) SetSortOrder(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkUpsertBulk) AddSortOrder(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateSortOrder() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateSortOrder()
	})
}

// SetURL sets the "url" field.
func (u *LinkUpsertBulk) SetURL(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateURL() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateURL()
	})
}

// SetAvatar sets the "avatar" field.
func (u *LinkUpsertBulk) SetAvatar(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateAvatar() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *LinkUpsertBulk) ClearAvatar() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.ClearAvatar()
	})
}

// SetStatus sets the "status" field.
func (u *LinkUpsertBulk) SetStatus(v entity.LinkStatus) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateStatus() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateStatus()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *LinkUpsertBulk) SetCategoryID(v uint) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateCategoryID() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *LinkUpsertBulk) ClearCategoryID() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.ClearCategoryID()
	})
}

// Exec executes the query.
func (u *LinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
