// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/postcategoryrelation"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostCategoryRelationCreate is the builder for creating a PostCategoryRelation entity.
type PostCategoryRelationCreate struct {
	config
	mutation *PostCategoryRelationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPostID sets the "post_id" field.
func (_c *PostCategoryRelationCreate) SetPostID(v uint) *PostCategoryRelationCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetPostCategoryID sets the "post_category_id" field.
func (_c *PostCategoryRelationCreate) SetPostCategoryID(v uint) *PostCategoryRelationCreate {
	_c.mutation.SetPostCategoryID(v)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PostCategoryRelationCreate) SetPost(v *Post) *PostCategoryRelationCreate {
	return _c.SetPostID(v.ID)
}

// SetCategoryID sets the "category" edge to the PostCategory entity by ID.
func (_c *PostCategoryRelationCreate) SetCategoryID(id uint) *PostCategoryRelationCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetCategory sets the "category" edge to the PostCategory entity.
func (_c *PostCategoryRelationCreate) SetCategory(v *PostCategory) *PostCategoryRelationCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the PostCategoryRelationMutation object of the builder.
func (_c *PostCategoryRelationCreate) Mutation() *PostCategoryRelationMutation {
	return _c.mutation
}

// Save creates the PostCategoryRelation in the database.
func (_c *PostCategoryRelationCreate) Save(ctx context.Context) (*PostCategoryRelation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCategoryRelationCreate) SaveX(ctx context.Context) *PostCategoryRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCategoryRelationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCategoryRelationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCategoryRelationCreate) check() error {
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostCategoryRelation.post_id"`)}
	}
	if _, ok := _c.mutation.PostCategoryID(); !ok {
		return &ValidationError{Name: "post_category_id", err: errors.New(`ent: missing required field "PostCategoryRelation.post_category_id"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostCategoryRelation.post"`)}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "PostCategoryRelation.category"`)}
	}
	return nil
}

func (_c *PostCategoryRelationCreate) sqlSave(ctx context.Context) (*PostCategoryRelation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *PostCategoryRelationCreate) createSpec() (*PostCategoryRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &PostCategoryRelation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(postcategoryrelation.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.PostTable,
			Columns: []string{postcategoryrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.CategoryTable,
			Columns: []string{postcategoryrelation.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostCategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostCategoryRelation.Create().
//		SetPostID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostCategoryRelationUpsert) {
//			SetPostID(v+v).
//		}).
//		Exec(ctx)
func (_c *PostCategoryRelationCreate) OnConflict(opts ...sql.ConflictOption) *PostCategoryRelationUpsertOne {
	_c.conflict = opts
	return &PostCategoryRelationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostCategoryRelationCreate) OnConflictColumns(columns ...string) *PostCategoryRelationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostCategoryRelationUpsertOne{
		create: _c,
	}
}

type (
	// PostCategoryRelationUpsertOne is the builder for "upsert"-ing
	//  one PostCategoryRelation node.
	PostCategoryRelationUpsertOne struct {
		create *PostCategoryRelationCreate
	}

	// PostCategoryRelationUpsert is the "OnConflict" setter.
	PostCategoryRelationUpsert struct {
		*sql.UpdateSet
	}
)

// SetPostID sets the "post_id" field.
func (u *PostCategoryRelationUpsert) SetPostID(v uint) *PostCategoryRelationUpsert {
	u.Set(postcategoryrelation.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsert) UpdatePostID() *PostCategoryRelationUpsert {
	u.SetExcluded(postcategoryrelation.FieldPostID)
	return u
}

// SetPostCategoryID sets the "post_category_id" field.
func (u *PostCategoryRelationUpsert) SetPostCategoryID(v uint) *PostCategoryRelationUpsert {
	u.Set(postcategoryrelation.FieldPostCategoryID, v)
	return u
}

// UpdatePostCategoryID sets the "post_category_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsert) UpdatePostCategoryID() *PostCategoryRelationUpsert {
	u.SetExcluded(postcategoryrelation.FieldPostCategoryID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PostCategoryRelationUpsertOne) UpdateNewValues() *PostCategoryRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PostCategoryRelationUpsertOne) Ignore() *PostCategoryRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostCategoryRelationUpsertOne) DoNothing() *PostCategoryRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostCategoryRelationCreate.OnConflict
// documentation for more info.
func (u *PostCategoryRelationUpsertOne) Update(set func(*PostCategoryRelationUpsert)) *PostCategoryRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostCategoryRelationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPostID sets the "post_id" field.
func (u *PostCategoryRelationUpsertOne) SetPostID(v uint) *PostCategoryRelationUpsertOne {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsertOne) UpdatePostID() *PostCategoryRelationUpsertOne {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.UpdatePostID()
	})
}

// SetPostCategoryID sets the "post_category_id" field.
func (u *PostCategoryRelationUpsertOne) SetPostCategoryID(v uint) *PostCategoryRelationUpsertOne {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.SetPostCategoryID(v)
	})
}

// UpdatePostCategoryID sets the "post_category_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsertOne) UpdatePostCategoryID() *PostCategoryRelationUpsertOne {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.UpdatePostCategoryID()
	})
}

// Exec executes the query.
func (u *PostCategoryRelationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostCategoryRelationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostCategoryRelationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// PostCategoryRelationCreateBulk is the builder for creating many PostCategoryRelation entities in bulk.
type PostCategoryRelationCreateBulk struct {
	config
	err      error
	builders []*PostCategoryRelationCreate
	conflict []sql.ConflictOption
}

// Save creates the PostCategoryRelation entities in the database.
func (_c *PostCategoryRelationCreateBulk) Save(ctx context.Context) ([]*PostCategoryRelation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostCategoryRelation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostCategoryRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCategoryRelationCreateBulk) SaveX(ctx context.Context) []*PostCategoryRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCategoryRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCategoryRelationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostCategoryRelation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostCategoryRelationUpsert) {
//			SetPostID(v+v).
//		}).
//		Exec(ctx)
func (_c *PostCategoryRelationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PostCategoryRelationUpsertBulk {
	_c.conflict = opts
	return &PostCategoryRelationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostCategoryRelationCreateBulk) OnConflictColumns(columns ...string) *PostCategoryRelationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostCategoryRelationUpsertBulk{
		create: _c,
	}
}

// PostCategoryRelationUpsertBulk is the builder for "upsert"-ing
// a bulk of PostCategoryRelation nodes.
type PostCategoryRelationUpsertBulk struct {
	create *PostCategoryRelationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PostCategoryRelationUpsertBulk) UpdateNewValues() *PostCategoryRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostCategoryRelation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PostCategoryRelationUpsertBulk) Ignore() *PostCategoryRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostCategoryRelationUpsertBulk) DoNothing() *PostCategoryRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostCategoryRelationCreateBulk.OnConflict
// documentation for more info.
func (u *PostCategoryRelationUpsertBulk) Update(set func(*PostCategoryRelationUpsert)) *PostCategoryRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostCategoryRelationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPostID sets the "post_id" field.
func (u *PostCategoryRelationUpsertBulk) SetPostID(v uint) *PostCategoryRelationUpsertBulk {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsertBulk) UpdatePostID() *PostCategoryRelationUpsertBulk {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.UpdatePostID()
	})
}

// SetPostCategoryID sets the "post_category_id" field.
func (u *PostCategoryRelationUpsertBulk) SetPostCategoryID(v uint) *PostCategoryRelationUpsertBulk {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.SetPostCategoryID(v)
	})
}

// UpdatePostCategoryID sets the "post_category_id" field to the value that was provided on create.
func (u *PostCategoryRelationUpsertBulk) UpdatePostCategoryID() *PostCategoryRelationUpsertBulk {
	return u.Update(func(s *PostCategoryRelationUpsert) {
		s.UpdatePostCategoryID()
	})
}

// Exec executes the query.
func (u *PostCategoryRelationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PostCategoryRelationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostCategoryRelationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostCategoryRelationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
