// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/posttag"
	"blog-server/ent/posttagrelation"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationCreate is the builder for creating a PostTagRelation entity.
type PostTagRelationCreate struct {
	config
	mutation *PostTagRelationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPostID sets the "post_id" field.
func (_c *PostTagRelationCreate) SetPostID(v uint) *PostTagRelationCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetPostTagID sets the "post_tag_id" field.
func (_c *PostTagRelationCreate) SetPostTagID(v uint) *PostTagRelationCreate {
	_c.mutation.SetPostTagID(v)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PostTagRelationCreate) SetPost(v *Post) *PostTagRelationCreate {
	return _c.SetPostID(v.ID)
}

// SetTagID sets the "tag" edge to the PostTag entity by ID.
func (_c *PostTagRelationCreate) SetTagID(id uint) *PostTagRelationCreate {
	_c.mutation.SetTagID(id)
	return _c
}

// SetTag sets the "tag" edge to the PostTag entity.
func (_c *PostTagRelationCreate) SetTag(v *PostTag) *PostTagRelationCreate {
	return _c.SetTagID(v.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (_c *PostTagRelationCreate) Mutation() *PostTagRelationMutation {
	return _c.mutation
}

// Save creates the PostTagRelation in the database.
func (_c *PostTagRelationCreate) Save(ctx context.Context) (*PostTagRelation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostTagRelationCreate) SaveX(ctx context.Context) *PostTagRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTagRelationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTagRelationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostTagRelationCreate) check() error {
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostTagRelation.post_id"`)}
	}
	if _, ok := _c.mutation.PostTagID(); !ok {
		return &ValidationError{Name: "post_tag_id", err: errors.New(`ent: missing required field "PostTagRelation.post_tag_id"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostTagRelation.post"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "PostTagRelation.tag"`)}
	}
	return nil
}

func (_c *PostTagRelationCreate) sqlSave(ctx context.Context) (*PostTagRelation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *PostTagRelationCreate) createSpec() (*PostTagRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &PostTagRelation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(posttagrelation.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostTagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostTagRelation.Create().
//		SetPostID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostTagRelationUpsert) {
//			SetPostID(v+v).
//		}).
//		Exec(ctx)
func (_c *PostTagRelationCreate) OnConflict(opts ...sql.ConflictOption) *PostTagRelationUpsertOne {
	_c.conflict = opts
	return &PostTagRelationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostTagRelationCreate) OnConflictColumns(columns ...string) *PostTagRelationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostTagRelationUpsertOne{
		create: _c,
	}
}

type (
	// PostTagRelationUpsertOne is the builder for "upsert"-ing
	//  one PostTagRelation node.
	PostTagRelationUpsertOne struct {
		create *PostTagRelationCreate
	}

	// PostTagRelationUpsert is the "OnConflict" setter.
	PostTagRelationUpsert struct {
		*sql.UpdateSet
	}
)

// SetPostID sets the "post_id" field.
func (u *PostTagRelationUpsert) SetPostID(v uint) *PostTagRelationUpsert {
	u.Set(posttagrelation.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTagRelationUpsert) UpdatePostID() *PostTagRelationUpsert {
	u.SetExcluded(posttagrelation.FieldPostID)
	return u
}

// SetPostTagID sets the "post_tag_id" field.
func (u *PostTagRelationUpsert) SetPostTagID(v uint) *PostTagRelationUpsert {
	u.Set(posttagrelation.FieldPostTagID, v)
	return u
}

// UpdatePostTagID sets the "post_tag_id" field to the value that was provided on create.
func (u *PostTagRelationUpsert) UpdatePostTagID() *PostTagRelationUpsert {
	u.SetExcluded(posttagrelation.FieldPostTagID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PostTagRelationUpsertOne) UpdateNewValues() *PostTagRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PostTagRelationUpsertOne) Ignore() *PostTagRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostTagRelationUpsertOne) DoNothing() *PostTagRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostTagRelationCreate.OnConflict
// documentation for more info.
func (u *PostTagRelationUpsertOne) Update(set func(*PostTagRelationUpsert)) *PostTagRelationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostTagRelationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPostID sets the "post_id" field.
func (u *PostTagRelationUpsertOne) SetPostID(v uint) *PostTagRelationUpsertOne {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTagRelationUpsertOne) UpdatePostID() *PostTagRelationUpsertOne {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.UpdatePostID()
	})
}

// SetPostTagID sets the "post_tag_id" field.
func (u *PostTagRelationUpsertOne) SetPostTagID(v uint) *PostTagRelationUpsertOne {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.SetPostTagID(v)
	})
}

// UpdatePostTagID sets the "post_tag_id" field to the value that was provided on create.
func (u *PostTagRelationUpsertOne) UpdatePostTagID() *PostTagRelationUpsertOne {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.UpdatePostTagID()
	})
}

// Exec executes the query.
func (u *PostTagRelationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostTagRelationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostTagRelationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// PostTagRelationCreateBulk is the builder for creating many PostTagRelation entities in bulk.
type PostTagRelationCreateBulk struct {
	config
	err      error
	builders []*PostTagRelationCreate
	conflict []sql.ConflictOption
}

// Save creates the PostTagRelation entities in the database.
func (_c *PostTagRelationCreateBulk) Save(ctx context.Context) ([]*PostTagRelation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostTagRelation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostTagRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostTagRelationCreateBulk) SaveX(ctx context.Context) []*PostTagRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTagRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTagRelationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PostTagRelation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PostTagRelationUpsert) {
//			SetPostID(v+v).
//		}).
//		Exec(ctx)
func (_c *PostTagRelationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PostTagRelationUpsertBulk {
	_c.conflict = opts
	return &PostTagRelationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PostTagRelationCreateBulk) OnConflictColumns(columns ...string) *PostTagRelationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PostTagRelationUpsertBulk{
		create: _c,
	}
}

// PostTagRelationUpsertBulk is the builder for "upsert"-ing
// a bulk of PostTagRelation nodes.
type PostTagRelationUpsertBulk struct {
	create *PostTagRelationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PostTagRelationUpsertBulk) UpdateNewValues() *PostTagRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PostTagRelation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PostTagRelationUpsertBulk) Ignore() *PostTagRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PostTagRelationUpsertBulk) DoNothing() *PostTagRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PostTagRelationCreateBulk.OnConflict
// documentation for more info.
func (u *PostTagRelationUpsertBulk) Update(set func(*PostTagRelationUpsert)) *PostTagRelationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PostTagRelationUpsert{UpdateSet: update})
	}))
	return u
}

// SetPostID sets the "post_id" field.
func (u *PostTagRelationUpsertBulk) SetPostID(v uint) *PostTagRelationUpsertBulk {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PostTagRelationUpsertBulk) UpdatePostID() *PostTagRelationUpsertBulk {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.UpdatePostID()
	})
}

// SetPostTagID sets the "post_tag_id" field.
func (u *PostTagRelationUpsertBulk) SetPostTagID(v uint) *PostTagRelationUpsertBulk {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.SetPostTagID(v)
	})
}

// UpdatePostTagID sets the "post_tag_id" field to the value that was provided on create.
func (u *PostTagRelationUpsertBulk) UpdatePostTagID() *PostTagRelationUpsertBulk {
	return u.Update(func(s *PostTagRelationUpsert) {
		s.UpdatePostTagID()
	})
}

// Exec executes the query.
func (u *PostTagRelationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PostTagRelationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PostTagRelationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PostTagRelationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
