// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/predicate"
	"blog-server/ent/site"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SiteUpdate) SetName(v string) *SiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableName(v *string) *SiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLogo sets the "logo" field.
func (_u *SiteUpdate) SetLogo(v string) *SiteUpdate {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableLogo(v *string) *SiteUpdate {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// ClearLogo clears the value of the "logo" field.
func (_u *SiteUpdate) ClearLogo() *SiteUpdate {
	_u.mutation.ClearLogo()
	return _u
}

// SetGreeting sets the "greeting" field.
func (_u *SiteUpdate) SetGreeting(v string) *SiteUpdate {
	_u.mutation.SetGreeting(v)
	return _u
}

// SetNillableGreeting sets the "greeting" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableGreeting(v *string) *SiteUpdate {
	if v != nil {
		_u.SetGreeting(*v)
	}
	return _u
}

// ClearGreeting clears the value of the "greeting" field.
func (_u *SiteUpdate) ClearGreeting() *SiteUpdate {
	_u.mutation.ClearGreeting()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SiteUpdate) SetDescription(v string) *SiteUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDescription(v *string) *SiteUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SiteUpdate) ClearDescription() *SiteUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SiteUpdate) SetCreatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableCreatedAt(v *time.Time) *SiteUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdate) SetUpdatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUpdatedAt(v *time.Time) *SiteUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(site.FieldLogo, field.TypeString, value)
	}
	if _u.mutation.LogoCleared() {
		_spec.ClearField(site.FieldLogo, field.TypeString)
	}
	if value, ok := _u.mutation.Greeting(); ok {
		_spec.SetField(site.FieldGreeting, field.TypeString, value)
	}
	if _u.mutation.GreetingCleared() {
		_spec.ClearField(site.FieldGreeting, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(site.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(site.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(site.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *SiteUpdateOne) SetName(v string) *SiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableName(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLogo sets the "logo" field.
func (_u *SiteUpdateOne) SetLogo(v string) *SiteUpdateOne {
	_u.mutation.SetLogo(v)
	return _u
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableLogo(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetLogo(*v)
	}
	return _u
}

// ClearLogo clears the value of the "logo" field.
func (_u *SiteUpdateOne) ClearLogo() *SiteUpdateOne {
	_u.mutation.ClearLogo()
	return _u
}

// SetGreeting sets the "greeting" field.
func (_u *SiteUpdateOne) SetGreeting(v string) *SiteUpdateOne {
	_u.mutation.SetGreeting(v)
	return _u
}

// SetNillableGreeting sets the "greeting" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableGreeting(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetGreeting(*v)
	}
	return _u
}

// ClearGreeting clears the value of the "greeting" field.
func (_u *SiteUpdateOne) ClearGreeting() *SiteUpdateOne {
	_u.mutation.ClearGreeting()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SiteUpdateOne) SetDescription(v string) *SiteUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDescription(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SiteUpdateOne) ClearDescription() *SiteUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SiteUpdateOne) SetCreatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableCreatedAt(v *time.Time) *SiteUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdateOne) SetUpdatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUpdatedAt(v *time.Time) *SiteUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logo(); ok {
		_spec.SetField(site.FieldLogo, field.TypeString, value)
	}
	if _u.mutation.LogoCleared() {
		_spec.ClearField(site.FieldLogo, field.TypeString)
	}
	if value, ok := _u.mutation.Greeting(); ok {
		_spec.SetField(site.FieldGreeting, field.TypeString, value)
	}
	if _u.mutation.GreetingCleared() {
		_spec.ClearField(site.FieldGreeting, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(site.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(site.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(site.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
