// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/site"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SiteCreate is the builder for creating a Site entity.
type SiteCreate struct {
	config
	mutation *SiteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SiteCreate) SetName(v string) *SiteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLogo sets the "logo" field.
func (_c *SiteCreate) SetLogo(v string) *SiteCreate {
	_c.mutation.SetLogo(v)
	return _c
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (_c *SiteCreate) SetNillableLogo(v *string) *SiteCreate {
	if v != nil {
		_c.SetLogo(*v)
	}
	return _c
}

// SetGreeting sets the "greeting" field.
func (_c *SiteCreate) SetGreeting(v string) *SiteCreate {
	_c.mutation.SetGreeting(v)
	return _c
}

// SetNillableGreeting sets the "greeting" field if the given value is not nil.
func (_c *SiteCreate) SetNillableGreeting(v *string) *SiteCreate {
	if v != nil {
		_c.SetGreeting(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SiteCreate) SetDescription(v string) *SiteCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SiteCreate) SetNillableDescription(v *string) *SiteCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SiteCreate) SetCreatedAt(v time.Time) *SiteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SiteCreate) SetNillableCreatedAt(v *time.Time) *SiteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SiteCreate) SetUpdatedAt(v time.Time) *SiteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SiteCreate) SetNillableUpdatedAt(v *time.Time) *SiteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SiteCreate) SetID(v int) *SiteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SiteCreate) SetNillableID(v *int) *SiteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SiteMutation object of the builder.
func (_c *SiteCreate) Mutation() *SiteMutation {
	return _c.mutation
}

// Save creates the Site in the database.
func (_c *SiteCreate) Save(ctx context.Context) (*Site, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteCreate) SaveX(ctx context.Context) *Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SiteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := site.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := site.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := site.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Site.name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Site.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Site.updated_at"`)}
	}
	return nil
}

func (_c *SiteCreate) sqlSave(ctx context.Context) (*Site, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteCreate) createSpec() (*Site, *sqlgraph.CreateSpec) {
	var (
		_node = &Site{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(site.Table, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Logo(); ok {
		_spec.SetField(site.FieldLogo, field.TypeString, value)
		_node.Logo = value
	}
	if value, ok := _c.mutation.Greeting(); ok {
		_spec.SetField(site.FieldGreeting, field.TypeString, value)
		_node.Greeting = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(site.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(site.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Site.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteCreate) OnConflict(opts ...sql.ConflictOption) *SiteUpsertOne {
	_c.conflict = opts
	return &SiteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteCreate) OnConflictColumns(columns ...string) *SiteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteUpsertOne{
		create: _c,
	}
}

type (
	// SiteUpsertOne is the builder for "upsert"-ing
	//  one Site node.
	SiteUpsertOne struct {
		create *SiteCreate
	}

	// SiteUpsert is the "OnConflict" setter.
	SiteUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SiteUpsert) SetName(v string) *SiteUpsert {
	u.Set(site.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SiteUpsert) UpdateName() *SiteUpsert {
	u.SetExcluded(site.FieldName)
	return u
}

// SetLogo sets the "logo" field.
func (u *SiteUpsert) SetLogo(v string) *SiteUpsert {
	u.Set(site.FieldLogo, v)
	return u
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *SiteUpsert) UpdateLogo() *SiteUpsert {
	u.SetExcluded(site.FieldLogo)
	return u
}

// ClearLogo clears the value of the "logo" field.
func (u *SiteUpsert) ClearLogo() *SiteUpsert {
	u.SetNull(site.FieldLogo)
	return u
}

// SetGreeting sets the "greeting" field.
func (u *SiteUpsert) SetGreeting(v string) *SiteUpsert {
	u.Set(site.FieldGreeting, v)
	return u
}

// UpdateGreeting sets the "greeting" field to the value that was provided on create.
func (u *SiteUpsert) UpdateGreeting() *SiteUpsert {
	u.SetExcluded(site.FieldGreeting)
	return u
}

// ClearGreeting clears the value of the "greeting" field.
func (u *SiteUpsert) ClearGreeting() *SiteUpsert {
	u.SetNull(site.FieldGreeting)
	return u
}

// SetDescription sets the "description" field.
func (u *SiteUpsert) SetDescription(v string) *SiteUpsert {
	u.Set(site.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SiteUpsert) UpdateDescription() *SiteUpsert {
	u.SetExcluded(site.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SiteUpsert) ClearDescription() *SiteUpsert {
	u.SetNull(site.FieldDescription)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SiteUpsert) SetCreatedAt(v time.Time) *SiteUpsert {
	u.Set(site.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SiteUpsert) UpdateCreatedAt() *SiteUpsert {
	u.SetExcluded(site.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteUpsert) SetUpdatedAt(v time.Time) *SiteUpsert {
	u.Set(site.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteUpsert) UpdateUpdatedAt() *SiteUpsert {
	u.SetExcluded(site.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(site.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SiteUpsertOne) UpdateNewValues() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(site.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SiteUpsertOne) Ignore() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteUpsertOne) DoNothing() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteCreate.OnConflict
// documentation for more info.
func (u *SiteUpsertOne) Update(set func(*SiteUpsert)) *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SiteUpsertOne) SetName(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateName() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateName()
	})
}

// SetLogo sets the "logo" field.
func (u *SiteUpsertOne) SetLogo(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateLogo() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateLogo()
	})
}

// ClearLogo clears the value of the "logo" field.
func (u *SiteUpsertOne) ClearLogo() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.ClearLogo()
	})
}

// SetGreeting sets the "greeting" field.
func (u *SiteUpsertOne) SetGreeting(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetGreeting(v)
	})
}

// UpdateGreeting sets the "greeting" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateGreeting() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateGreeting()
	})
}

// ClearGreeting clears the value of the "greeting" field.
func (u *SiteUpsertOne) ClearGreeting() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.ClearGreeting()
	})
}

// SetDescription sets the "description" field.
func (u *SiteUpsertOne) SetDescription(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateDescription() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SiteUpsertOne) ClearDescription() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.ClearDescription()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SiteUpsertOne) SetCreatedAt(v time.Time) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateCreatedAt() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteUpsertOne) SetUpdatedAt(v time.Time) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateUpdatedAt() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SiteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SiteUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SiteUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SiteCreateBulk is the builder for creating many Site entities in bulk.
type SiteCreateBulk struct {
	config
	err      error
	builders []*SiteCreate
	conflict []sql.ConflictOption
}

// Save creates the Site entities in the database.
func (_c *SiteCreateBulk) Save(ctx context.Context) ([]*Site, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Site, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteCreateBulk) SaveX(ctx context.Context) []*Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Site.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteCreateBulk) OnConflict(opts ...sql.ConflictOption) *SiteUpsertBulk {
	_c.conflict = opts
	return &SiteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteCreateBulk) OnConflictColumns(columns ...string) *SiteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteUpsertBulk{
		create: _c,
	}
}

// SiteUpsertBulk is the builder for "upsert"-ing
// a bulk of Site nodes.
type SiteUpsertBulk struct {
	create *SiteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(site.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SiteUpsertBulk) UpdateNewValues() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(site.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SiteUpsertBulk) Ignore() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteUpsertBulk) DoNothing() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteCreateBulk.OnConflict
// documentation for more info.
func (u *SiteUpsertBulk) Update(set func(*SiteUpsert)) *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SiteUpsertBulk) SetName(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateName() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateName()
	})
}

// SetLogo sets the "logo" field.
func (u *SiteUpsertBulk) SetLogo(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateLogo() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateLogo()
	})
}

// ClearLogo clears the value of the "logo" field.
func (u *SiteUpsertBulk) ClearLogo() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.ClearLogo()
	})
}

// SetGreeting sets the "greeting" field.
func (u *SiteUpsertBulk) SetGreeting(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetGreeting(v)
	})
}

// UpdateGreeting sets the "greeting" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateGreeting() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateGreeting()
	})
}

// ClearGreeting clears the value of the "greeting" field.
func (u *SiteUpsertBulk) ClearGreeting() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.ClearGreeting()
	})
}

// SetDescription sets the "description" field.
func (u *SiteUpsertBulk) SetDescription(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateDescription() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SiteUpsertBulk) ClearDescription() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.ClearDescription()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SiteUpsertBulk) SetCreatedAt(v time.Time) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateCreatedAt() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteUpsertBulk) SetUpdatedAt(v time.Time) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateUpdatedAt() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SiteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SiteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
