// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/system"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemCreate is the builder for creating a System entity.
type SystemCreate struct {
	config
	mutation *SystemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInitialized sets the "initialized" field.
func (_c *SystemCreate) SetInitialized(v bool) *SystemCreate {
	_c.mutation.SetInitialized(v)
	return _c
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_c *SystemCreate) SetNillableInitialized(v *bool) *SystemCreate {
	if v != nil {
		_c.SetInitialized(*v)
	}
	return _c
}

// SetInitializedAt sets the "initialized_at" field.
func (_c *SystemCreate) SetInitializedAt(v time.Time) *SystemCreate {
	_c.mutation.SetInitializedAt(v)
	return _c
}

// SetNillableInitializedAt sets the "initialized_at" field if the given value is not nil.
func (_c *SystemCreate) SetNillableInitializedAt(v *time.Time) *SystemCreate {
	if v != nil {
		_c.SetInitializedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemCreate) SetCreatedAt(v time.Time) *SystemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemCreate) SetNillableCreatedAt(v *time.Time) *SystemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemCreate) SetUpdatedAt(v time.Time) *SystemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemCreate) SetNillableUpdatedAt(v *time.Time) *SystemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SystemCreate) SetID(v int) *SystemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SystemCreate) SetNillableID(v *int) *SystemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SystemMutation object of the builder.
func (_c *SystemCreate) Mutation() *SystemMutation {
	return _c.mutation
}

// Save creates the System in the database.
func (_c *SystemCreate) Save(ctx context.Context) (*System, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemCreate) SaveX(ctx context.Context) *System {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemCreate) defaults() {
	if _, ok := _c.mutation.Initialized(); !ok {
		v := system.DefaultInitialized
		_c.mutation.SetInitialized(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := system.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := system.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := system.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemCreate) check() error {
	if _, ok := _c.mutation.Initialized(); !ok {
		return &ValidationError{Name: "initialized", err: errors.New(`ent: missing required field "System.initialized"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "System.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "System.updated_at"`)}
	}
	return nil
}

func (_c *SystemCreate) sqlSave(ctx context.Context) (*System, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemCreate) createSpec() (*System, *sqlgraph.CreateSpec) {
	var (
		_node = &System{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(system.Table, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Initialized(); ok {
		_spec.SetField(system.FieldInitialized, field.TypeBool, value)
		_node.Initialized = value
	}
	if value, ok := _c.mutation.InitializedAt(); ok {
		_spec.SetField(system.FieldInitializedAt, field.TypeTime, value)
		_node.InitializedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(system.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(system.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.System.Create().
//		SetInitialized(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemUpsert) {
//			SetInitialized(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemCreate) OnConflict(opts ...sql.ConflictOption) *SystemUpsertOne {
	_c.conflict = opts
	return &SystemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemCreate) OnConflictColumns(columns ...string) *SystemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemUpsertOne{
		create: _c,
	}
}

type (
	// SystemUpsertOne is the builder for "upsert"-ing
	//  one System node.
	SystemUpsertOne struct {
		create *SystemCreate
	}

	// SystemUpsert is the "OnConflict" setter.
	SystemUpsert struct {
		*sql.UpdateSet
	}
)

// SetInitialized sets the "initialized" field.
func (u *SystemUpsert) SetInitialized(v bool) *SystemUpsert {
	u.Set(system.FieldInitialized, v)
	return u
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *SystemUpsert) UpdateInitialized() *SystemUpsert {
	u.SetExcluded(system.FieldInitialized)
	return u
}

// SetInitializedAt sets the "initialized_at" field.
func (u *SystemUpsert) SetInitializedAt(v time.Time) *SystemUpsert {
	u.Set(system.FieldInitializedAt, v)
	return u
}

// UpdateInitializedAt sets the "initialized_at" field to the value that was provided on create.
func (u *SystemUpsert) UpdateInitializedAt() *SystemUpsert {
	u.SetExcluded(system.FieldInitializedAt)
	return u
}

// ClearInitializedAt clears the value of the "initialized_at" field.
func (u *SystemUpsert) ClearInitializedAt() *SystemUpsert {
	u.SetNull(system.FieldInitializedAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SystemUpsert) SetCreatedAt(v time.Time) *SystemUpsert {
	u.Set(system.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemUpsert) UpdateCreatedAt() *SystemUpsert {
	u.SetExcluded(system.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemUpsert) SetUpdatedAt(v time.Time) *SystemUpsert {
	u.Set(system.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemUpsert) UpdateUpdatedAt() *SystemUpsert {
	u.SetExcluded(system.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(system.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemUpsertOne) UpdateNewValues() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(system.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.System.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemUpsertOne) Ignore() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemUpsertOne) DoNothing() *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemCreate.OnConflict
// documentation for more info.
func (u *SystemUpsertOne) Update(set func(*SystemUpsert)) *SystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetInitialized sets the "initialized" field.
func (u *SystemUpsertOne) SetInitialized(v bool) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetInitialized(v)
	})
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateInitialized() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateInitialized()
	})
}

// SetInitializedAt sets the "initialized_at" field.
func (u *SystemUpsertOne) SetInitializedAt(v time.Time) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetInitializedAt(v)
	})
}

// UpdateInitializedAt sets the "initialized_at" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateInitializedAt() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateInitializedAt()
	})
}

// ClearInitializedAt clears the value of the "initialized_at" field.
func (u *SystemUpsertOne) ClearInitializedAt() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.ClearInitializedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SystemUpsertOne) SetCreatedAt(v time.Time) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateCreatedAt() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemUpsertOne) SetUpdatedAt(v time.Time) *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemUpsertOne) UpdateUpdatedAt() *SystemUpsertOne {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SystemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemCreateBulk is the builder for creating many System entities in bulk.
type SystemCreateBulk struct {
	config
	err      error
	builders []*SystemCreate
	conflict []sql.ConflictOption
}

// Save creates the System entities in the database.
func (_c *SystemCreateBulk) Save(ctx context.Context) ([]*System, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*System, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemCreateBulk) SaveX(ctx context.Context) []*System {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.System.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemUpsert) {
//			SetInitialized(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemUpsertBulk {
	_c.conflict = opts
	return &SystemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemCreateBulk) OnConflictColumns(columns ...string) *SystemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemUpsertBulk{
		create: _c,
	}
}

// SystemUpsertBulk is the builder for "upsert"-ing
// a bulk of System nodes.
type SystemUpsertBulk struct {
	create *SystemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(system.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemUpsertBulk) UpdateNewValues() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(system.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.System.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemUpsertBulk) Ignore() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemUpsertBulk) DoNothing() *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemCreateBulk.OnConflict
// documentation for more info.
func (u *SystemUpsertBulk) Update(set func(*SystemUpsert)) *SystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetInitialized sets the "initialized" field.
func (u *SystemUpsertBulk) SetInitialized(v bool) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetInitialized(v)
	})
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateInitialized() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateInitialized()
	})
}

// SetInitializedAt sets the "initialized_at" field.
func (u *SystemUpsertBulk) SetInitializedAt(v time.Time) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetInitializedAt(v)
	})
}

// UpdateInitializedAt sets the "initialized_at" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateInitializedAt() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateInitializedAt()
	})
}

// ClearInitializedAt clears the value of the "initialized_at" field.
func (u *SystemUpsertBulk) ClearInitializedAt() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.ClearInitializedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SystemUpsertBulk) SetCreatedAt(v time.Time) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateCreatedAt() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemUpsertBulk) SetUpdatedAt(v time.Time) *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemUpsertBulk) UpdateUpdatedAt() *SystemUpsertBulk {
	return u.Update(func(s *SystemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SystemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
