// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/predicate"
	"blog-server/ent/system"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemUpdate is the builder for updating System entities.
type SystemUpdate struct {
	config
	hooks     []Hook
	mutation  *SystemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SystemUpdate builder.
func (_u *SystemUpdate) Where(ps ...predicate.System) *SystemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInitialized sets the "initialized" field.
func (_u *SystemUpdate) SetInitialized(v bool) *SystemUpdate {
	_u.mutation.SetInitialized(v)
	return _u
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableInitialized(v *bool) *SystemUpdate {
	if v != nil {
		_u.SetInitialized(*v)
	}
	return _u
}

// SetInitializedAt sets the "initialized_at" field.
func (_u *SystemUpdate) SetInitializedAt(v time.Time) *SystemUpdate {
	_u.mutation.SetInitializedAt(v)
	return _u
}

// SetNillableInitializedAt sets the "initialized_at" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableInitializedAt(v *time.Time) *SystemUpdate {
	if v != nil {
		_u.SetInitializedAt(*v)
	}
	return _u
}

// ClearInitializedAt clears the value of the "initialized_at" field.
func (_u *SystemUpdate) ClearInitializedAt() *SystemUpdate {
	_u.mutation.ClearInitializedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SystemUpdate) SetCreatedAt(v time.Time) *SystemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableCreatedAt(v *time.Time) *SystemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemUpdate) SetUpdatedAt(v time.Time) *SystemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SystemUpdate) SetNillableUpdatedAt(v *time.Time) *SystemUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SystemMutation object of the builder.
func (_u *SystemUpdate) Mutation() *SystemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Initialized(); ok {
		_spec.SetField(system.FieldInitialized, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InitializedAt(); ok {
		_spec.SetField(system.FieldInitializedAt, field.TypeTime, value)
	}
	if _u.mutation.InitializedAtCleared() {
		_spec.ClearField(system.FieldInitializedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(system.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(system.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemUpdateOne is the builder for updating a single System entity.
type SystemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SystemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetInitialized sets the "initialized" field.
func (_u *SystemUpdateOne) SetInitialized(v bool) *SystemUpdateOne {
	_u.mutation.SetInitialized(v)
	return _u
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableInitialized(v *bool) *SystemUpdateOne {
	if v != nil {
		_u.SetInitialized(*v)
	}
	return _u
}

// SetInitializedAt sets the "initialized_at" field.
func (_u *SystemUpdateOne) SetInitializedAt(v time.Time) *SystemUpdateOne {
	_u.mutation.SetInitializedAt(v)
	return _u
}

// SetNillableInitializedAt sets the "initialized_at" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableInitializedAt(v *time.Time) *SystemUpdateOne {
	if v != nil {
		_u.SetInitializedAt(*v)
	}
	return _u
}

// ClearInitializedAt clears the value of the "initialized_at" field.
func (_u *SystemUpdateOne) ClearInitializedAt() *SystemUpdateOne {
	_u.mutation.ClearInitializedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SystemUpdateOne) SetCreatedAt(v time.Time) *SystemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableCreatedAt(v *time.Time) *SystemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemUpdateOne) SetUpdatedAt(v time.Time) *SystemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SystemUpdateOne) SetNillableUpdatedAt(v *time.Time) *SystemUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the SystemMutation object of the builder.
func (_u *SystemUpdateOne) Mutation() *SystemMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemUpdate builder.
func (_u *SystemUpdateOne) Where(ps ...predicate.System) *SystemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemUpdateOne) Select(field string, fields ...string) *SystemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated System entity.
func (_u *SystemUpdateOne) Save(ctx context.Context) (*System, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUpdateOne) SaveX(ctx context.Context) *System {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemUpdateOne) sqlSave(ctx context.Context) (_node *System, err error) {
	_spec := sqlgraph.NewUpdateSpec(system.Table, system.Columns, sqlgraph.NewFieldSpec(system.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "System.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, system.FieldID)
		for _, f := range fields {
			if !system.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != system.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Initialized(); ok {
		_spec.SetField(system.FieldInitialized, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InitializedAt(); ok {
		_spec.SetField(system.FieldInitializedAt, field.TypeTime, value)
	}
	if _u.mutation.InitializedAtCleared() {
		_spec.ClearField(system.FieldInitializedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(system.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(system.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &System{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{system.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
