-- +goose Up

CREATE TABLE comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ
);

CREATE TABLE link_categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
name VARCHAR NOT NULL,
sort_order BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX link_categories_name_key
ON link_categories (name);

CREATE TABLE links (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
description VARCHAR,
enabled BOOLEAN NOT NULL DEFAULT FALSE,
name VARCHAR NOT NULL,
sort_order BIGINT NOT NULL DEFAULT 0,
url VARCHAR NOT NULL,
avatar VARCHAR,
status VARCHAR NOT NULL DEFAULT 'normal',
category_id BIGINT
);

CREATE UNIQUE INDEX links_url_key
ON links (url);

CREATE TABLE post_categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
name VARCHAR NOT NULL,
slug VARCHAR NOT NULL
);

CREATE UNIQUE INDEX post_categories_name_key
ON post_categories (name);

CREATE UNIQUE INDEX post_categories_slug_key
ON post_categories (slug);

CREATE TABLE post_tags (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
name VARCHAR NOT NULL,
slug VARCHAR NOT NULL
);

CREATE UNIQUE INDEX post_tags_name_key
ON post_tags (name);

CREATE UNIQUE INDEX post_tags_slug_key
ON post_tags (slug);

CREATE TABLE users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
uuid UUID NOT NULL,
avatar VARCHAR,
email VARCHAR NOT NULL,
password VARCHAR NOT NULL,
role VARCHAR NOT NULL DEFAULT 'reader',
username VARCHAR NOT NULL
);

CREATE UNIQUE INDEX users_email_key
ON users (email);

CREATE UNIQUE INDEX users_uuid_key
ON users (uuid);

CREATE TABLE posts (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created_at TIMESTAMPTZ NOT NULL,
updated_at TIMESTAMPTZ NOT NULL,
deleted_at TIMESTAMPTZ,
title VARCHAR NOT NULL,
summary VARCHAR,
content TEXT NOT NULL,
cover VARCHAR,
read_time_minutes BIGINT NOT NULL,
view_count BIGINT NOT NULL DEFAULT 0,
status VARCHAR NOT NULL DEFAULT 'draft',
published_at TIMESTAMPTZ,
user_id BIGINT NOT NULL
);

CREATE TABLE post_category_relations (
post_id BIGINT NOT NULL,
post_category_id BIGINT NOT NULL,
PRIMARY KEY (post_id, post_category_id)
);

CREATE TABLE post_tag_relations (
post_id BIGINT NOT NULL,
post_tag_id BIGINT NOT NULL,
PRIMARY KEY (post_id, post_tag_id)
);

-- +goose Down

-- Baseline migration is intentionally irreversible.
