package main

import (
	"context"
	"fmt"
	"log"

	"blog-server/config"
	"blog-server/datastore"
	"blog-server/ent"
	"blog-server/ent/migrate"
	"blog-server/logger"
)

func main() {
	cfg := config.MustLoad()
	log := logger.NewLogger(cfg)
	ds, err := datastore.NewDataStore(cfg, log)
	if err != nil {
		log.Fatal(fmt.Sprintf("failed to connect to database: %v", err))
	}
	defer func() {
		if err := ds.Close(); err != nil {
			log.Info(fmt.Sprintf("failed to close database client: %v", err))
		}
	}()
	createSchema(ds.Client(context.Background()))
}

func createSchema(client *ent.Client) {
	ctx := context.Background()

	if err := client.Schema.Create(
		ctx,
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
		migrate.WithForeignKeys(true),

		migrate.WithFuncs(func(next migrate.Creator) migrate.Creator {
			return migrate.CreateFunc(func(ctx context.Context, m *migrate.Migrate) error {
				// 👇 先修复数据库结构（SERIAL -> IDENTITY）
				if _, err := m.DB.ExecContext(ctx, `
					ALTER TABLE link_categories
					ALTER COLUMN id DROP DEFAULT;
				`); err != nil {
					return err
				}

				if _, err := m.DB.ExecContext(ctx, `
					DO $$
					BEGIN
						IF EXISTS (
							SELECT 1 FROM pg_class WHERE relname = 'link_categories_id_seq'
						) THEN
							DROP SEQUENCE link_categories_id_seq;
						END IF;
					END $$;
				`); err != nil {
					return err
				}

				if _, err := m.DB.ExecContext(ctx, `
					ALTER TABLE link_categories
					ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
				`); err != nil {
					return err
				}

				// 👇 再执行 ent 默认迁移
				return next.Create(ctx, m)
			})
		}),
	); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}
}
