// Code generated by ent, DO NOT EDIT.

package system

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the system type in the database.
	Label = "system"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInitialized holds the string denoting the initialized field in the database.
	FieldInitialized = "initialized"
	// FieldInitializedAt holds the string denoting the initialized_at field in the database.
	FieldInitializedAt = "initialized_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the system in the database.
	Table = "systems"
)

// Columns holds all SQL columns for system fields.
var Columns = []string{
	FieldID,
	FieldInitialized,
	FieldInitializedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInitialized holds the default value on creation for the "initialized" field.
	DefaultInitialized bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int
)

// OrderOption defines the ordering options for the System queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInitialized orders the results by the initialized field.
func ByInitialized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitialized, opts...).ToFunc()
}

// ByInitializedAt orders the results by the initialized_at field.
func ByInitializedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitializedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
