// Code generated by ent, DO NOT EDIT.

package system

import (
	"blog-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.System {
	return predicate.System(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.System {
	return predicate.System(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.System {
	return predicate.System(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.System {
	return predicate.System(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.System {
	return predicate.System(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.System {
	return predicate.System(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.System {
	return predicate.System(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.System {
	return predicate.System(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.System {
	return predicate.System(sql.FieldLTE(FieldID, id))
}

// Initialized applies equality check predicate on the "initialized" field. It's identical to InitializedEQ.
func Initialized(v bool) predicate.System {
	return predicate.System(sql.FieldEQ(FieldInitialized, v))
}

// InitializedAt applies equality check predicate on the "initialized_at" field. It's identical to InitializedAtEQ.
func InitializedAt(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldInitializedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldUpdatedAt, v))
}

// InitializedEQ applies the EQ predicate on the "initialized" field.
func InitializedEQ(v bool) predicate.System {
	return predicate.System(sql.FieldEQ(FieldInitialized, v))
}

// InitializedNEQ applies the NEQ predicate on the "initialized" field.
func InitializedNEQ(v bool) predicate.System {
	return predicate.System(sql.FieldNEQ(FieldInitialized, v))
}

// InitializedAtEQ applies the EQ predicate on the "initialized_at" field.
func InitializedAtEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldInitializedAt, v))
}

// InitializedAtNEQ applies the NEQ predicate on the "initialized_at" field.
func InitializedAtNEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldNEQ(FieldInitializedAt, v))
}

// InitializedAtIn applies the In predicate on the "initialized_at" field.
func InitializedAtIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldIn(FieldInitializedAt, vs...))
}

// InitializedAtNotIn applies the NotIn predicate on the "initialized_at" field.
func InitializedAtNotIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldNotIn(FieldInitializedAt, vs...))
}

// InitializedAtGT applies the GT predicate on the "initialized_at" field.
func InitializedAtGT(v time.Time) predicate.System {
	return predicate.System(sql.FieldGT(FieldInitializedAt, v))
}

// InitializedAtGTE applies the GTE predicate on the "initialized_at" field.
func InitializedAtGTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldGTE(FieldInitializedAt, v))
}

// InitializedAtLT applies the LT predicate on the "initialized_at" field.
func InitializedAtLT(v time.Time) predicate.System {
	return predicate.System(sql.FieldLT(FieldInitializedAt, v))
}

// InitializedAtLTE applies the LTE predicate on the "initialized_at" field.
func InitializedAtLTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldLTE(FieldInitializedAt, v))
}

// InitializedAtIsNil applies the IsNil predicate on the "initialized_at" field.
func InitializedAtIsNil() predicate.System {
	return predicate.System(sql.FieldIsNull(FieldInitializedAt))
}

// InitializedAtNotNil applies the NotNil predicate on the "initialized_at" field.
func InitializedAtNotNil() predicate.System {
	return predicate.System(sql.FieldNotNull(FieldInitializedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.System {
	return predicate.System(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.System {
	return predicate.System(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.System {
	return predicate.System(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.System {
	return predicate.System(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.System {
	return predicate.System(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.System {
	return predicate.System(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.System {
	return predicate.System(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.System) predicate.System {
	return predicate.System(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.System) predicate.System {
	return predicate.System(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.System) predicate.System {
	return predicate.System(sql.NotPredicates(p))
}
