# name: Full Deploy (Frontend * Backend)
#
# on:
#   push:
#     branches:
#       - master
#
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Set up Podman
#         run: |
#           sudo apt update
#           sudo apt install -y podman
#
#       - name: Cache Podman layers for frontend and backend
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/podman
#           key: ${{ runner.os }}-podman-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-podman-
#
#       - name: Build Frontend Podman image
#         run: |
#           cd frontend
#           podman build -t blog-frontend:latest .
#
#       - name: Build Backend Podman image
#         run: |
#           cd backend
#           podman build -t blog-backend:latest .
#
#       - name: Save Frontend Podman image as tar
#         run: |
#           podman save -o blog-frontend.tar blog-frontend:latest
#
#       - name: Save Backend Podman image as tar
#         run: |
#           podman save -o blog-backend.tar blog-backend:latest
#
#       - name: Upload Frontend images to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "blog-frontend.tar"
#           target: "/home/${{ secrets.SSH_USERNAME }}/blog-images"
#
#       - name: Upload Backend images to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "blog-backend.tar"
#           target: "/home/${{ secrets.SSH_USERNAME }}/blog-images"
#
#       - name: Upload docker-compose.yml to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "docker-compose.yml"
#           target: "/home/${{ secrets.SSH_USERNAME }}/blog-images"
#
#       - name: Deploy and start containers on server
#         run: |
#           ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
#             cd /home/${{ secrets.SSH_USERNAME }}/blog-images
#             podman-compose down  # 停止现有容器
#             podman-compose up -d  # 启动新容器
#           EOF
